export const countries = [
  {
    id: 'us',
    name: 'United States',
    flag: '🇺🇸',
    image: 'https://justinkelefas.com/wp-content/uploads/2022/04/New-York-City-Manhattan-Skyline-Sample.jpg',
    description: 'The land of opportunity with pathways for students, highly skilled workers, and investors.',
    region: 'N. America',
    tags: ['H-1B VISA', 'F-1 STUDENT'],
    features: ['Study-friendly', 'Work visa availability'],
    currency: { code: 'USD', symbol: '$', name: 'US Dollar' },
  },
  {
    id: 'ca',
    name: 'Canada',
    flag: '🇨🇦',
    image: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=600&h=400&fit=crop&auto=format',
    description: 'A leading destination for skilled workers with streamlined PR pathways.',
    region: 'N. America',
    tags: ['PR AVAILABLE', 'IELTS REQUIRED'],
    features: ['PR options', 'Work visa availability', 'Study-friendly'],
    currency: { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar' },
  },
  {
    id: 'cn',
    name: 'China',
    flag: '🇨🇳',
    image: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=600&h=400&fit=crop&auto=format',
    description: 'A rising global power with business visas and growing opportunities for skilled professionals.',
    region: 'Asia Pacific',
    tags: ['BUSINESS VISA', 'WORK PERMIT'],
    features: ['Work visa availability', 'Study-friendly'],
    currency: { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    flag: '🇬🇧',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600&h=400&fit=crop&auto=format',
    description: 'World-class education and diverse work opportunities in a historic setting.',
    region: 'Europe',
    tags: ['SKILLED WORKER', 'STUDENT VISA'],
    features: ['Study-friendly', 'Work visa availability'],
    currency: { code: 'GBP', symbol: '£', name: 'British Pound' },
  },
  {
    id: 'de',
    name: 'Germany',
    flag: '🇩🇪',
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=600&h=400&fit=crop&auto=format',
    description: "Europe's economic engine offering Opportunity Cards for job seekers.",
    region: 'Europe',
    tags: ['JOB SEEKER VISA', 'FREE EDUCATION'],
    features: ['Study-friendly', 'Work visa availability', 'PR options'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
  },
  {
    id: 'fr',
    name: 'France',
    flag: '🇫🇷',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&h=400&fit=crop&auto=format',
    description: 'A top destination for art, culture, and education with a welcoming student visa program.',
    region: 'Europe',
    tags: ['STUDENT VISA', 'TALENT PASSPORT'],
    features: ['Study-friendly', 'Work visa availability'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
  },
  {
    id: 'nl',
    name: 'Netherlands',
    flag: '🇳🇱',
    image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?w=600&h=400&fit=crop&auto=format',
    description: 'A global hub for tech and innovation with English-taught programs and startup visas.',
    region: 'Europe',
    tags: ['STARTUP VISA', 'HIGHLY SKILLED'],
    features: ['Work visa availability', 'Study-friendly'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
  },
  {
    id: 'se',
    name: 'Sweden',
    flag: '🇸🇪',
    image: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=600&h=400&fit=crop&auto=format',
    description: 'High quality of life, strong welfare system, and growing tech industry.',
    region: 'Europe',
    tags: ['WORK PERMIT', 'STUDY PERMIT'],
    features: ['Study-friendly', 'Work visa availability', 'PR options'],
    currency: { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  },
  {
    id: 'au',
    name: 'Australia',
    flag: '🇦🇺',
    image: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=600&h=400&fit=crop&auto=format',
    description: 'Sunshine, opportunity, and one of the best quality of life indexes globally.',
    region: 'Oceania',
    tags: ['POINTS BASED', 'PR PATHWAY'],
    features: ['PR options', 'Work visa availability', 'Study-friendly'],
    currency: { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  },
  {
    id: 'nz',
    name: 'New Zealand',
    flag: '🇳🇿',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=600&h=400&fit=crop&auto=format',
    description: 'Stunning landscapes and a welcoming immigration system with clear PR pathways.',
    region: 'Oceania',
    tags: ['SKILLED MIGRANT', 'STUDENT VISA'],
    features: ['PR options', 'Work visa availability', 'Study-friendly'],
    currency: { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  },
  {
    id: 'jp',
    name: 'Japan',
    flag: '🇯🇵',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&h=400&fit=crop&auto=format',
    description: 'A unique blend of tradition and innovation with growing immigration pathways.',
    region: 'Asia Pacific',
    tags: ['WORK VISA', 'CULTURAL VISA'],
    features: ['Work visa availability'],
    currency: { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  },
  {
    id: 'sg',
    name: 'Singapore',
    flag: '🇸🇬',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&h=400&fit=crop&auto=format',
    description: "Asia's business hub with fast-track employment passes for professionals.",
    region: 'Asia Pacific',
    tags: ['EMPLOYMENT PASS', 'BUSINESS HUB'],
    features: ['Work visa availability'],
    currency: { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  },
  {
    id: 'ae',
    name: 'UAE',
    flag: '🇦🇪',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&h=400&fit=crop&auto=format',
    description: 'Tax-free living with golden visa options for investors and skilled professionals.',
    region: 'Asia Pacific',
    tags: ['GOLDEN VISA', 'TAX FREE'],
    features: ['Work visa availability'],
    currency: { code: 'AED', symbol: 'AED', name: 'UAE Dirham' },
  },
  {
    id: 'in',
    name: 'India',
    flag: '🇮🇳',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&h=400&fit=crop&auto=format',
    description: 'A fast-growing economy with e-Visa facilities and opportunities in tech and business.',
    region: 'Asia Pacific',
    tags: ['E-VISA', 'BUSINESS VISA'],
    features: ['Study-friendly', 'Work visa availability'],
    currency: { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  },
  {
    id: 'kr',
    name: 'South Korea',
    flag: '🇰🇷',
    image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=600&h=400&fit=crop&auto=format',
    description: 'A tech powerhouse with K-ETA digital entry and growing expat community.',
    region: 'Asia Pacific',
    tags: ['D-2 STUDENT', 'E-7 WORK'],
    features: ['Study-friendly', 'Work visa availability'],
    currency: { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  },
  {
    id: 'pt',
    name: 'Portugal',
    flag: '🇵🇹',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&h=400&fit=crop&auto=format',
    description: "Europe's most popular digital nomad destination with Golden Visa and D7 programs.",
    region: 'Europe',
    tags: ['GOLDEN VISA', 'DIGITAL NOMAD'],
    features: ['PR options', 'Work visa availability', 'Study-friendly'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
  },
  {
    id: 'es',
    name: 'Spain',
    flag: '🇪🇸',
    image: 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=600&h=400&fit=crop&auto=format',
    description: 'Vibrant culture, warm climate, and a Digital Nomad Visa for remote workers.',
    region: 'Europe',
    tags: ['DIGITAL NOMAD', 'STUDENT VISA'],
    features: ['Study-friendly', 'Work visa availability'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
  },
  {
    id: 'ch',
    name: 'Switzerland',
    flag: '🇨🇭',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=600&h=400&fit=crop&auto=format',
    description: 'High salaries, top universities, and a stable economy in the heart of Europe.',
    region: 'Europe',
    tags: ['WORK PERMIT', 'STUDENT VISA'],
    features: ['Study-friendly', 'Work visa availability'],
    currency: { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  },
  {
    id: 'mx',
    name: 'Mexico',
    flag: '🇲🇽',
    image: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=600&h=400&fit=crop&auto=format',
    description: 'A vibrant culture with affordable living and Temporary Resident visa options.',
    region: 'N. America',
    tags: ['TEMPORARY RESIDENT', 'DIGITAL NOMAD'],
    features: ['Work visa availability'],
    currency: { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso' },
  },
  {
    id: 'br',
    name: 'Brazil',
    flag: '🇧🇷',
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600&h=400&fit=crop&auto=format',
    description: "South America's largest economy with investment and work visa opportunities.",
    region: 'S. America',
    tags: ['WORK VISA', 'INVESTMENT VISA'],
    features: ['Work visa availability'],
    currency: { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  },
  {
    id: 'za',
    name: 'South Africa',
    flag: '🇿🇦',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=600&h=400&fit=crop&auto=format',
    description: 'Diverse landscapes and a critical skills visa for qualified professionals.',
    region: 'Africa',
    tags: ['CRITICAL SKILLS', 'BUSINESS VISA'],
    features: ['Work visa availability', 'Study-friendly'],
    currency: { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  },
];

export const regions = ['Europe', 'N. America', 'Asia Pacific', 'Oceania', 'S. America', 'Africa'];

export const visaTypes = {
  tourism: { label: 'Tourism', icon: 'Palmtree', color: 'bg-amber-100 text-amber-700' },
  study: { label: 'Study', icon: 'GraduationCap', color: 'bg-blue-100 text-blue-700' },
  work: { label: 'Work', icon: 'Briefcase', color: 'bg-green-100 text-green-700' },
  business: { label: 'Business', icon: 'Building2', color: 'bg-purple-100 text-purple-700' },
};

export const purposes = [
  { value: 'tourism', label: 'Tourism', description: 'Travel & sightseeing', icon: '✈️' },
  { value: 'study', label: 'Study', description: 'Education & research', icon: '🎓' },
  { value: 'work', label: 'Work', description: 'Employment & career', icon: '💼' },
  { value: 'business', label: 'Business', description: 'Investment & trade', icon: '🏢' },
];
